### ISSUE TITLE
Hardcodeos / Manejos de configuraciones

### ISSUE THREAD

**Issue by matricali** [los-pollitos/rating#3]
Los datos de conexion a la base de datos estan hardcodeados en el codigo:

```
$container->set(
    'db',
    function () {
        return new Mysql(
            [
                'host' => 'db',
                'username' => 'root',
                'password' => 'root',
                'dbname' => 'rating',
            ]
        );
    }
);
```

Evaluar colocar una configuracion

**Comment by Pronesti** [comment]
Listo, se agrego un config.ini donde se pueden guardar las configuraciones y se lo agrego al gitignore

**Comment by matricali** [comment]
@Pronesti La mejor práctica para trabajar con configuraciones es utilizar arreglos nativos de PHP, al utilizar INI estar realizando un parsing que no es necesario.

**Comment by matricali** [comment]
PD: No olvides referenciar los issues en los mensajes de commit, esto sirve para dejar un historico de los cambios relacionados a esta tarea


Tipo de referencia | Referencia en bruto | Vínculo acortado
-- | -- | --
URL de propuesta o solicitud de extracción | https://github.com/jlord/sheetsee.js/issues/26 | #26
# y número de propuesta o solicitud de extracción | #26 | #26
GH y número de propuesta y solicitud de extracción | GH-26 | GH-26
Nombre de usuario/N.º de repositorio y número de propuesta o solicitud de extracción. | jlord/sheetsee.js#26 | jlord/sheetsee.js#26
Organization_name/Repository# y número propuesta o solicitud de extracción | github/linguist#4039 | github/linguist#4039

**Comment by Pronesti** [comment]
Ahora si

**Comment by matricali** [comment]
No es recomendable asignarlo a una variable
Imaginate este caso, donde necesitas cargar multiples configuraciones. Que pondrias? $settings, $settings2, $settings3 ?

Lo recomendado es hacer un retorno del objeto, require e include retornan la referencia.

Ejemplo:
```
<?php
return [
    'database' => [
        'adapter'  => 'Mysql',
        'host'     => 'db',
        'username' => 'root',
        'password' => 'root',
        'dbname'   => 'rating'
    ],
     'phalcon' => [
        'modelsDir'      => '../app/models/',
        'viewsDir'       => '../app/views/'
    ],
]; 
```
Entonces la forma de consumirlo seria la siguiente:
```
$config = new Config(require '../config/config.php');
```

**Comment by Pronesti** [comment]
Listo, se retorna directamente el array.
