### ISSUE TITLE
Listo, se agrego un config.ini donde se pueden guardar las configuraciones y se lo agrego al gitignore

### ISSUE THREAD

**Issue by elmistico1187** [los-pollitos/rating#4]
Listo, se agrego un config.ini donde se pueden guardar las configuraciones y se lo agrego al gitignore

_Originally posted by @Pronesti in https://github.com/los-pollitos/rating/issues/3#issuecomment-615261651_

**Comment by elmistico1187** [comment]
[](url)

**Comment by matricali** [comment]
?

**Comment by elmistico1187** [comment]
Duplicate of #
